### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by AndiDemon** [FraLuca/STSGCN#13]
Hello,
It is an awesome work and achievement.
Thank you for providing the code.
I would like to ask about the unit in the evaluation method.
In the paper it is use the mm unit. If I am not wrong by reading the code of the utils/loss_funcs.py, 
It does not show any unit in mm or pixels. Am I wrong? or do you use the pixels first and then convert it to mm in the paper?
Thank you.
Best regards.

**Comment by FraLuca** [comment]
Hi AndiDemon,

We're happy you enjoyed our work! 
You are right, we use mm unit for the MPJPE loss. In particular, in the loss function, we input skeleton joint positions in Euclidean coordinates (x,y,z). So we never use images or conversion pixel to mm. 
You can consider the resulting value of the loss in mm.
I hope this will clear your doubt.
Luca

**Comment by AndiDemon** [comment]
Thank you for your quick respond,
I understand, considering the input which is quite complicated 
I tried to run the code on CPU yesterday. 
I need to do some changes on the code regarding the cuda() function.
But the program run well after that.

Best regards,
