### ISSUE TITLE
Models for training

### ISSUE THREAD

**Issue by Evm7** [FraLuca/STSGCN#14]
Dear author,

First of all congratulations for the paper and for the results.
As I have checked from your "checkpoints" directory, it seems that we have one weight for for each frame that we want to predict. Is that right? That means, for predicting frames from 4 to 25 do we need to use different weights, or with one we can obtain all the results published in the paper?

Really thanks for your time

**Comment by FraLuca** [comment]
Hi,
Sorry for the late reply. 
You're right, we use a different model for each time horizon.
Following also previous literature, this approach can make a difference in performance.

Thanks for your question

**Comment by emedinac** [comment]
@Dean-UQ I think the link is broken.
